export const PRODUCT_REQ = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_FAIL = 'PRODUCT_LIST_FAIL'
export const PRODUCT_SUCCESS = 'PRODUCT_LIST_SUCCESS'

export const PRODUCT_DETAILS_REQ = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
